### ISSUE TITLE
chess-input does not handle promotions

### ISSUE THREAD

**Issue by mlang** [jwiegley/emacs-chess#4]
chess-input does not prompt for the promotion piece, and the generated ply missed the :promote keyword.
This is later caught in chess-ply-create, which notices the missing :promote keyword.
chess-input should prompt for the promotion piece and correctly set it in the resulting ply object.
chess-ics is also missing promotion piece sending, mostly because it was never present in chess-input ...

**Comment by epeld** [comment]
I just ran into this problem, testing out `emacs chess` for the first time. To me, the error happened in `chess-display` instead of `chess-input` but it is the same problem.

The docstring for `chess-ply-create` says:
```
"Create a ply from the given POSITION by applying the supplied CHANGES.
This function will guarantee the resulting ply is legal, and will also
annotate the ply with :check or other modifiers as necessary.  It will
also extend castling, and will prompt for a promotion piece.

Note: Do not pass in the rook move if CHANGES represents a castling
maneuver."
```
(notice this part: **"[..] and will prompt for a promotion piece"**).

So my question is, is the solution to replace the line that says `(chess-error 'ambiguous-promotion)`?

**Comment by epeld** [comment]
Created a commit that tries to fix this: https://github.com/jwiegley/emacs-chess/pull/12
